addressbook_create:
    pattern:  /addressbook/create
    defaults: { _controller: ExampleAddressBookBundle:People:create }

addressbook_list:
    pattern:  /addressbook
    defaults: { _controller: ExampleAddressBookBundle:People:list }
    
addressbook_update:
    pattern:  /addressbook/update/{id}
    defaults: { _controller: ExampleAddressBookBundle:People:update }
    
addressbook_delete:
    pattern:  /addressbook/delete/{id}
    defaults: { _controller: ExampleAddressBookBundle:People:delete }
