parameters:
#    example_address_book.example.class: Example\AddressBookBundle\Example

services:
#    example_address_book.example:
#        class: %example_address_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
